version: '2'
services:
    web:
      build:
        context: .
        dockerfile: dockerfile
      restart: unless-stopped
      tty: true
      image: abcd
      command:  python app.py
      ports:
        - "2226:5000"
      links:
        - db
      depends_on:
        - db
      networks:
        - main

    db:
      image: mysql:5.7.22
      restart: unless-stopped
      tty: true
      environment:
        MYSQL_DATABASE: my_db
        MYSQL_ROOT_PASSWORD: 123
      ports:
      - "13306:3306"
      networks:
        - main

    

networks:
  main:
    driver: bridge

volumes:
  scan_file:

