version: '2'
services:

    db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123
      networks:
        - main

    web:
      restart: always
      image: docker_register
      command:  python app.py
      ports:
        - "2226:5000"
      links:
        - db
      depends_on:
        - db
      networks:
        - main

networks:
  main:
    driver: bridge

volumes:
  scan_file:
