version: '2'
services:
    web:
      build:
        context: .
        dockerfile: dockerfile
      restart: unless-stopped
      ports:
        - "2226:5000"
      links:
        - db
      depends_on:
        - db
      networks:
        - main
    db:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: list_db
        MYSQL_ROOT_PASSWORD: 123
      ports:
      - "13306:3306"  
      networks:
        - main

    

networks:
  main:
    driver: bridge

volumes:
  scan_file:
