FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y python-pip python-dev build-essential
RUN apt-get install -y libmysqlclient-dev

COPY . /list_docker
WORKDIR /list_docker

RUN pip install -r requirements.txt
CMD ["python", "app.py"]